### ISSUE TITLE
https://fedbook.cn/无法访问

### ISSUE THREAD

**Issue by haha987456** [wenyuan/fedbook#33]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/120309051/206901423-676b80e0-31c1-4817-b0f6-9fef0ee1296d.png">

提示需要登录

**Comment by wenyuan** [comment]
目前已恢复成免登录访问

**Comment by wenyuan** [comment]
这个域名过期不续费了，目前采用GitHub Pages访问在线小册吧~
